platform :ios, '13.0'

target 'WebView' do
use_frameworks!

pod 'SnapKit', '~> 5.0.1'
pod 'PKHUD', '~> 5.3.0'
pod 'NVActivityIndicatorView', '~> 5.0.0'
pod 'IQKeyboardManagerSwift', '~> 6.5.5'
pod 'WebViewJavascriptBridge', '~> 6.0'

end
